routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/imoveis/remove/{id}', 'ImovelController@remover')->name('imoveis.remove');
Route::resource('imoveis', 'ImovelController');

app/Imovel.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Imovel extends Model
{
    protected $fillable = [
        "descricao", "logradouroEndereco", "bairroEndereco", "numeroEndereco", "cepEndereco", "cidadeEndereco", "preco", "qtdQuartos", "tipo", "finalidade"
    ];

    protected $table = "imoveis";
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/ImovelController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
//importar a model de Imovel
use App\Imovel;
use Validator;



class ImovelController extends Controller
{
    //Validando o imovel
    protected function validarImovel($request){
        $validator = Validator::make($request->all(), [
            "descricao" => "required",
            "logradouroEndereco" => "required",
            "bairroEndereco" => "required",
            "numeroEndereco" => "required | numeric",
            "cepEndereco" => "required | numeric",
            "cidadeEndereco" => "required",
            "preco" => "required | numeric",
            "qtdQuartos" => "required | numeric",
            "tipo" => "required",
            "finalidade" => "required"
        ]);

        return $validator;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    //Listando os imoveis na página de index
    public function index()
    {   
        //Recuperando todos os imoveis do banco de dados e guardando na variável $imoveis.
        $imoveis = Imovel::all();
        //Retornamos a lista de imoveis do banco de dados para que estes sejam listados para o usuário.
        return view('imoveis.index', compact('imoveis'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('imoveis.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {   
        /*
        verificando se os dados enviados através do formulário
        são válidos.
        */
        $validator = $this->validarImovel($request);
        if($validator->fails()){
            return redirect()->back()->withErrors($validator->errors());
        }

        //cadastrando um Imovel
        $dados = $request->all();
        Imovel::create($dados);
        return redirect()->route('imoveis.index');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {   
        //Retornando o imóvel pelo id
        $imovel = Imovel::find($id);
        //exibindo detalhes do imóvel
        return view('imoveis.show', compact('imovel'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $imovel = Imovel::find($id);
        return view('imoveis.edit', compact('imovel'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = $this->validarImovel($request);

        if($validator->fails()) {
           return redirect()->back()->withErrors($validator->errors());
        }

        $imovel = Imovel::find($id);
        $dados = $request->all();
        $imovel->update($dados);
        return redirect()->route('imoveis.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Imovel::find($id)->delete();
        return redirect()->route('imoveis.index');
    }

    public function remover($id)
    {
        $imovel = Imovel::find($id);
        return view('imoveis.remove', compact('imovel'));
    }
}

resources/views/imoveis/create.blade.php
@extends('shared.base')
@section('content')
    
    @if($errors->any())
        <div class="alert alert-danger" role="alert">
            @foreach($errors->all() as $error)
                {{ $error }} <br/>
            @endforeach
        </div>
    @endif

    <div class="panel panel-default">
        <div class="panel-heading"><h3>Cadastre o Imóvel</h3></div>
        <div class="panel-body">

        <form method="post" action="{{route ('imoveis.store')}}">
            {{ csrf_field() }}
            <h4>Dados do Imóvel</h4>
            <hr>
            <div class="form-group">
                <label for="descricao">Descrição</label>
                <input type="text" class="form-control" placeholder="Descrição" name="descricao" required>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="preco">Preço</label>
                        <input type="text" class="form-control" placeholder="Preço" name="preco" required>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="qtdQuartos">Quantidade de Quartos</label>
                        <input type="number" class="form-control" placeholder="Quantidade de Quartos" required name="qtdQuartos">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="tipo">Tipo de Imóvel</label>
                        <select class="form-control" name="tipo" required>
                            <option>Apartamento</option>
                            <option>Casa</option>
                            <option>Kitnet</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="qtdQuartos">finalidade do Imóvel</label>
                        <select class="form-control" name="finalidade" required>
                            <option>Venda</opttion>
                            <option>Locação</opttion>
                        </select>
                    </div>
                </div>
            </div>
            <h4>Endereço</h4>
            <hr>
                <div class="form-group">
                    <label for="logradouroEndereco">Logradouro</label>
                    <input type="text" class="form-control" placeholder="Logradouro" required name="logradouroEndereco">
                </div>
            <div class="row">
                <div class="col-md-10">
                    <div class="form-group">
                        <label for="BairroEndereco">Bairro</label>
                        <input type="text" class="form-control" placeholder="Bairro" required name="bairroEndereco">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="numero">Número</label>
                            <input type="number" class="form-control" placeholder="Número" required name="numeroEndereco">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="cidadeEndereco">Cidade</label>
                        <input type="text" class="form-control" placeholder="Cidade" required name="cidadeEndereco">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="cepEndereco">CEP</label>
                        <input type="text" class="form-control" placeholder="CEP" required name="cepEndereco">
                    </div>
                </div>
            </div>
            <a href="{{ url()->previous() }}" class="btn btn-default">Voltar</a>
            <button type="submit" class="btn btn-primary">Cadastrar</button>
        </form>
        </div>
    </div>
@endsection

resources/views/imoveis/edit.blade.php
@extends('shared.base')
@section('content')

    @if($errors->any())
        <div class="alert alert-danger" role="alert">
            @foreach($errors->all() as $error)
                {{ $error }} <br>
            @endforeach
        </div>
    @endif

    <div class="panel panel-default">
        <div class="panel-heading"><h3>Edite o Imóvel</h3></div>
        <div class="panel-body">

        <form method="post" action="{{route ('imoveis.update', $imovel->id)}}">
            <input type="hidden" name="_method" value="PUT">
            {{ csrf_field() }}
            <h4>Dados do Imóvel</h4>
            <hr>
            <div class="form-group">
                <label for="descricao">Descrição</label>
                <input type="text" class="form-control" placeholder="Descrição" name="descricao" required value="{{$imovel->descricao}}">
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="preco">Preço</label>
                        <input type="text" class="form-control" placeholder="Preço" name="preco" required value="{{$imovel->preco}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="qtdQuartos">Quantidade de Quartos</label>
                        <input type="number" class="form-control" placeholder="Quantidade de Quartos" required name="qtdQuartos" 
                        value="{{$imovel->qtdQuartos}}">
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="tipo">Tipo de Imóvel</label>
                        <select class="form-control" name="tipo" required>
                            <option {{($imovel->tipo == 'apartamento' ? 'selected' : '')}}>Apartamento</option>
                            <option {{$imovel->tipo == 'casa' ? 'selected' : ''}}>Casa</option>
                            <option {{$imovel->tipo == 'kitnet' ? 'selected' : ''}}>Kitnet</option>
                        </select>
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="qtdQuartos">finalidade do Imóvel</label>
                        <select class="form-control" name="finalidade" required>
                            <option {{($imovel->finalidade == 'venda' ? 'selected' : '')}}>Venda</opttion>
                            <option {{($imovel->finalidade == 'locacao' ? 'selected' : '')}}>Locação</opttion>
                        </select>
                    </div>
                </div>
            </div>
            <h4>Endereço</h4>
            <hr>
                <div class="form-group">
                    <label for="logradouroEndereco">Logradouro</label>
                    <input type="text" class="form-control" placeholder="Logradouro" required name="logradouroEndereco"
                    value="{{$imovel->logradouroEndereco}}">
                </div>
            <div class="row">
                <div class="col-md-10">
                    <div class="form-group">
                        <label for="BairroEndereco">Bairro</label>
                        <input type="text" class="form-control" placeholder="Bairro" required name="bairroEndereco"
                        value="{{$imovel->bairroEndereco}}">
                    </div>
                </div>
                <div class="row">
                    <div class="col-md-2">
                        <div class="form-group">
                            <label for="numero">Número</label>
                            <input type="number" class="form-control" placeholder="Número" required name="numeroEndereco"
                            value="{{$imovel->numeroEndereco}}">
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="cidadeEndereco">Cidade</label>
                        <input type="text" class="form-control" placeholder="Cidade" required name="cidadeEndereco"
                        value="{{$imovel->cidadeEndereco}}">
                    </div>
                </div>
                <div class="col-md-6">
                    <div class="form-group">
                        <label for="cepEndereco">CEP</label>
                        <input type="text" class="form-control" placeholder="CEP" required name="cepEndereco"
                        value="{{$imovel->cepEndereco}}">
                    </div>
                </div>
            </div>
            <a href="{{ url()->previous() }}" class="btn btn-default">Voltar</a>
            <button type="submit" class="btn btn-primary">Editar</button>
        </form>
        </div>
    </div>
@endsection

resources/views/imoveis/index.blade.php
@extends('shared.base')
@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Lista de Imóveis</div>
        <div class="row">
            <div class="col-md-12">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>Descrição</th>
                            <th>Cidade</th>
                            <th>Preço</th>
                            <th>Finalidade</th>
                            <th>Tipo</th>
                            <th>Ações</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($imoveis as $imovel)
                            <tr>
                                <td>{{$imovel->descricao}}</td>
                                <td>{{$imovel->cidadeEndereco}}</td>
                                <td>{{$imovel->preco}}</td>
                                <td>{{$imovel->finalidade}}</td>
                                <td>{{$imovel->tipo}}</td>
                                <td>
                                    <a href="{{route('imoveis.edit', $imovel->id)}}"><i class="glyphicon glyphicon-pencil"></i></a>
                                    <a href="{{route('imoveis.remove', $imovel->id)}}"><i class="glyphicon glyphicon-trash"></i></a>
                                    <a href="{{route('imoveis.show', $imovel->id)}}"><i class="glyphicon glyphicon-zoom-in"></i></a>
                                </td>
                            </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
    <a href="{{route('imoveis.create')}}"><button class="btn btn-primary">Adicionar</button></a>
@endsection

resources/views/imoveis/remove.blade.php
@extends('shared.base')
@section('content')
    
    <div class="panel panel-default">
        <div class="panel-heading">Remover o imóvel</div>
        <div class="panel-body">
            <form method="post" action="{{route('imoveis.destroy', $imovel->id)}}">
            {{ csrf_field() }}
                <input type="hidden" name="_method" value="DELETE">
                <div class="row">
                    <div class="col-md-12">
                        <h4>Tem certeza que deseja remover o imóvel</h4>
                        <hr>
                        <h4>Sobre o imóvel</h4>
                        <p>Descrição: {{$imovel->descricao}}</p>
                        <p>Preco: {{number_format($imovel->preco, 2, ',', ',')}}</p>
                        <p>Quantidade de Quartos: {{$imovel->qtdQuartos}}</p>
                        <p>Tipo: {{$imovel->tipo}}</p>
                        <p>Finalidade: {{$imovel->finalidade}}</p>
                        <hr>
                        <h4>Endereço</h4>
                        <p>Logradouro: {{$imovel->logradouroEndereco}}</p>
                        <p>Bairro: {{$imovel->bairroEndereco}}</p>
                        <p>Numero: {{$imovel->numeroEndereco}}</p>
                        <p>CEP: {{$imovel->cepEndereco}}</p>
                        <p>Cidade: {{$imovel->cidadeEndereco}}</p>
                    </div>
                </div>
                <button type="submit" class="btn btn-danger">Remover</button>
                <a href="{{ url()->previous() }}" class="btn btn-default">Cancelar</a>
            </form>
        </div>
    </div>

@endsection

resources/views/imoveis/show.blade.php
@extends('shared.base')
@section('content')
    <div class="panel panel-default">
        <div class="panel-heading">Detalhes do Imóvel</div>
        <div class="panel-body">
            <div class="row">
                <div class="col-md-12">
                    <h4>Sobre o Imóvel</h4>
                    <p>Descrição: {{$imovel->descricao}}</p>
                    <p>Preço: R$ {{number_format($imovel->preco, 2, ',', ',')}}</p>
                    <p>Quantidade de Quartos: {{$imovel->qtdQuartos}}</p>
                    <p>Tipo: {{$imovel->tipo}}</p>
                    <p>Finalidade: {{$imovel->finalidade}}</p>
                    <hr>
                    <h4>Endereço</h4>
                    <p>Logradouro: {{$imovel->logradouroEndereco}}</p>
                    <p>Bairro: {{$imovel->bairroEndereco}}</p>
                    <p>Número: {{$imovel->numeroEndereco}}</p>
                    <p>Cep: {{$imovel->cepEndereco}}</p>
                    <p>Cidade: {{$imovel->cidadeEndereco}}</p>
                </div>
            </div>
        </div>
    </div>
    <a href="{{ url()->previous() }}" class="btn btn-default">Voltar</a>
@endsection

resources/views/shared/base.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">

    <title>Administração de Imóveis</title>

    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <script src="https://code.jquery.com/jquery-3.2.1.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body { padding-top: 70px; }
    </style>
</head>

<body>
    
    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">Inicio</a>
            </div>
            <div id="navbar" class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">Todos</a></li>
                    <li><a href="#">Apartamentos</a></li>
                    <li><a href="#">Casas</a></li>
                    <li><a href="#">Kitnet</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container">
        @yield('content')
    </div>
</body>
</html>